<!-- begin project_meta_override block -->
    <meta name="cmg:siteId" content="statesman">
    <meta name="cmg:siteType" content="free">
    <meta name="cmg:siteDomain" content="statesman.com">
    <meta name="cmg:product" content="www.statesman.com">
    <meta name="cmg:siteSection" content="News">
    <meta name="cmg:category" content="Local">
    <meta name="cmg:subcategory" content="Custom-Viewer-for-DocumentCloud">
    <meta name="cmg:mainSection" content="/news/local">
    <meta name="cmg:topics" content="aasinteractive, documentcloud viewer">
<!-- end project_meta_override block -->